<<<<<<< HEAD
# Storage type may be file or database
=======
# Storage type may be file or mysql
>>>>>>> rewrite
storage-type: file
# SQL Settings
sql:
  driver: mysql
  host: localhost
  port: 3306
  database: database-name
  use-ssl: false
<<<<<<< HEAD
  user: database-user
=======
  user: mysql-user
>>>>>>> rewrite
  password: super-strong-password